[package]
name = "r2d2_sqlite_neonphog"
version = "0.1.0"
authors = ["Jovansonlee Cesar<ivanceras@gmail.com>", "Hugo Woesthuis <hugo@woesthuis.eu>"]
license = "MIT"
description = "SQLite and SQLCipher support for the r2d2 connection pool"
repository = "https://github.com/neonphog/r2d2-sqlite"
documentation = "https://docs.rs/r2d2_sqlite_neonphog/"
keywords = ["sqlite", "r2d2", "pool"]
edition = "2018"

[lib]
name = "r2d2_sqlite"
path = "src/lib.rs"
test = false



[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
r2d2 = "0.8"

[dependencies.rusqlite]
version = "0.29"

[dev-dependencies]
tempdir = "0.3"

[dev-dependencies.rusqlite]
version = "0.29"
features = ["trace"]


[features]
bundled = [ "rusqlite/bundled" ]
bundled-sqlcipher = ["rusqlite/bundled-sqlcipher"]
